# Cloudflare Pages configuration for staging environment
name = "h5-games-static-staging"
compatibility_date = "2025-01-19"

[build]
command = "npm run build"
publish = "dist"

# Environment variables for staging
[vars]
NODE_ENV = "staging"
ENVIRONMENT = "staging"

# Custom headers for optimization (staging)
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-Environment = "staging"

# Cache static assets (shorter cache for staging)
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=86400"

# Cache games.json for shorter time in staging
[[headers]]
for = "/games.json"
[headers.values]
Cache-Control = "public, max-age=300"

# Security headers for iframe content
[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "frame-ancestors 'self'; frame-src https: data:;"

# Staging-specific redirects (if needed)
# [[redirects]]
# from = "/staging-test/*"
# to = "/:splat"
# status = 200